loss_config_list:
  - loss_type: "state_reconstruction"
    name: "state_reconstruction"
    weight: 2.0

  - loss_type: "action_reconstruction"
    name: "action_reconstruction"
    weight: 1.0

  - loss_type: "forward"
    name: "forward"
    weight: 1.0

  - loss_type: "state_condensation"
    name: "state_condensation"
    weight: 25.0

  - loss_type: "action_condensation"
    name: "action_condensation"
    weight: 25.0

  - loss_type: "smoothness"
    name: "smoothness"
    weight: 10.0

  - loss_type: "state_dispersion"
    name: "state_dispersion"
    weight: 1.0
    num_samples: 16

  - loss_type: "action_dispersion"
    name: "action_dispersion"
    weight: 1.0
    num_samples: 16

edge_config_list:
  - source: "state_reconstruction"
    target: "forward"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "action_reconstruction"
    target: "forward"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "state_reconstruction"
    target: "state_condensation"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "state_reconstruction"
    target: "action_condensation"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "action_reconstruction"
    target: "state_condensation"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "action_reconstruction"
    target: "action_condensation"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "forward"
    target: "smoothness"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "state_condensation"
    target: "smoothness"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "action_condensation"
    target: "smoothness"
    gate_config:
      gate_type: "spike"
      sharpness: 1e4
      center: 0.0
  - source: "smoothness"
    target: "state_dispersion"
    gate_config:
      gate_type: "spike"
      sharpness: 1e8
      center: 0.0
  - source: "smoothness"
    target: "action_dispersion"
    gate_config:
      gate_type: "spike"
      sharpness: 1e8
      center: 0.0
