checkpoint_dir: checkpoints
checkpoint_count: 3
save_every: 1
eval_every: 1
use_wandb: False

learning_rate: 2.5e-4

rollouts: 256
epochs: 64
batch_size: 64
traj_per_rollout: 1024
rollout_length: 64
target_net_tau: 0.05

seed: 0

net_config:
  latent_state_dim: 6
  state_dim: 6

  latent_action_dim: 2
  action_dim: 2

  state_encoder_layers: [64, 64]
  action_encoder_layers: [64, 64]

  state_decoder_layers: [64, 64]
  action_decoder_layers: [64, 64]

  temporal_encoder_min_freq: 0.015625
  temporal_encoder_max_freq: 0.5

  transition_model_n_layers: 2
  transition_model_latent_dim: 128
  transition_model_n_heads: 4

  latent_state_radius: 3.0
  latent_action_radius: 2.0

loss_config:
  state_reconstruction_loss_config:
    weight: 1.0
  action_reconstruction_loss_config:
    weight: 1.0
  forward_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -3.0
  state_condensation_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -5.0
  action_condensation_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -5.0
  smoothness_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -5.0
  state_dispersion_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -5.0
    num_samples: 16
  action_dispersion_loss_config:
    weight: 1.0
    sharpness: 1.0
    center: -5.0
    num_samples: 16
