defaults:
  - _self_
  - loss_config: default

checkpoint_dir: checkpoints
checkpoint_count: 3
save_every: 1
eval_every: 1
use_wandb: False

learning_rate: 1.0e-4

rollouts: 256
epochs: 64
batch_size: 64
traj_per_rollout: 1024
rollout_length: 64
target_net_tau: 0.05

seed: 0

net_config:
  latent_state_dim: 6
  state_dim: 6

  latent_action_dim: 2
  action_dim: 2

  state_encoder_layers: [1024, 512, 256, 128]
  action_encoder_layers: [1024, 512, 256, 64]

  state_decoder_layers: [1024, 512, 256, 128]
  action_decoder_layers: [1024, 512, 256, 64]

  temporal_encoder_min_freq: 0.015625 # 1/64
  temporal_encoder_max_freq: 0.5 # 1/2

  transition_model_n_layers: 2
  transition_model_latent_dim: 128
  transition_model_n_heads: 4

  latent_state_radius: 3.0
  latent_action_radius: 2.0
